# Generated by Django 4.0.4 on 2022-06-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreims', '0002_alter_book_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetail',
            name='book',
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='book',
            field=models.ManyToManyField(to='bookstoreims.book'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='stock_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detail_stock_name', to='bookstoreims.stock'),
        ),
    ]
