# Generated by Django 4.0.4 on 2022-06-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreims', '0003_remove_stockdetail_book_stockdetail_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='stock_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail_stock_name', to='bookstoreims.stock'),
        ),
    ]
