# Generated by Django 4.0.4 on 2022-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreims', '0004_alter_stockdetail_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='books',
            field=models.ManyToManyField(related_name='stock_books', to='bookstoreims.book'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StockDetail',
        ),
    ]
