# Generated by Django 4.0.4 on 2022-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreims', '0005_stock_books_alter_stock_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='stock_books', to='bookstoreims.book'),
        ),
    ]
