# Generated by Django 4.0.5 on 2022-06-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreims', '0007_alter_stock_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Stocks'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='books',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_books', to='bookstoreims.book'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_units',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_units', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='bookstoreims.stock')),
            ],
            options={
                'verbose_name_plural': 'StockHistory',
                'ordering': ['-date'],
            },
        ),
    ]
